---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1003
      - PGID=1002
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /home/dap/temp:/config
      - /home/dap/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped