apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: crossfits-tkc
spec:
  distribution:
    version: v1.21
  topology:
    controlPlane:
      class: guaranteed-small
      count: 3
      storageClass: kubernetes-storage-policy
    workers:
      class: best-effort-medium
      count: 5
      storageClass: kubernetes-storage-policy
  settings:
    storage:
      classes: ["kubernetes-storage-policy"]              #Named PVC storage classes
      defaultClass: kubernetes-storage-policy                     #Default PVC storage class