apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: calibre-web-config-pvc
  name: calibre-web-config-pvc
spec:
  #storageClassName: one-node-vsan-policy
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
