apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: calibre-web-books-pvc
  name: calibre-web-books-pvc
spec:
  storageClassName: ""
  #volumeName: crossfits-web-books-pvc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
status: {}
