apiVersion: v1
kind: ConfigMap
metadata:
  name: inadyn-cfgmap
data:
  inadyn.conf: |
    provider cloudflare:1 {
      username = dpitts.us
      password = CHANGE_ME
      hostname = { bw.dpitts.us, ha.dpitts.us, dpitts.us }
      ttl = 1
      proxied = true
    }